from enum import Enum


class JobStatus(str, Enum):
    CREATED = "CREATED"
    SCHEDULED = "SCHEDULED"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    RETRYING = "RETRYING"
    COMPLETED = "COMPLETED"
    DEAD = "DEAD"
    CANCELLED = "CANCELLED"


class WorkerStatus(str, Enum):
    STARTING = "STARTING"
    IDLE = "IDLE"
    BUSY = "BUSY"
    DEAD = "DEAD"
    STOPPED = "STOPPED"


class AttemptStatus(str, Enum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ABANDONED = "ABANDONED"


class JobEventType(str, Enum):
    JOB_CREATED = "JOB_CREATED"
    JOB_QUEUED = "JOB_QUEUED"
    JOB_SCHEDULED = "JOB_SCHEDULED"
    JOB_CLAIMED = "JOB_CLAIMED"
    JOB_STARTED = "JOB_STARTED"
    JOB_PROGRESS_UPDATED = "JOB_PROGRESS_UPDATED"
    JOB_COMPLETED = "JOB_COMPLETED"
    JOB_ATTEMPT_FAILED = "JOB_ATTEMPT_FAILED"
    JOB_RETRY_SCHEDULED = "JOB_RETRY_SCHEDULED"
    JOB_DEAD = "JOB_DEAD"
    JOB_CANCELLED = "JOB_CANCELLED"
    JOB_REPLAYED = "JOB_REPLAYED"
    JOB_LEASE_RENEWED = "JOB_LEASE_RENEWED"
    JOB_LEASE_EXPIRED = "JOB_LEASE_EXPIRED"
    JOB_RECOVERED = "JOB_RECOVERED"